version: '3'
services:
  db:
    image: learn_docker_ror_mysql
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: "my-pw"
    volumes:
      - ./mysql/datadir:/var/lib/mysql
  app:
    image: learn_docker_ror_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rorapp:/rorapp
    ports:
      - "3000:3000"
    network_mode: "bridge"
    links:
      - db
  nginx:
    image: learn_docker_ror_nginx
    volumes:
      - ./nginx/rorapp.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 80:80 
    network_mode: "bridge"
